### ISSUE TITLE
Fails to package application for Linux in v3.4.2

### ISSUE THREAD

**Issue by ragouel** [tagspaces/tagspaces#1094]
Running yarn package-linux fails with 

` ⨯ Application entry file "main.prod.js" in the "tagspaces/src/builds/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.`

1. Download [v.3.4.2](https://github.com/tagspaces/tagspaces/archive/v3.4.2.tar.gz)
2. Extract and cd into tagspaces-3.4.2/ 
3. run `yarn install`; `yarn install-ext`; `yarn package`

fails with ...

>yarn run v1.22.2
$ electron-builder --linux --config resources/builder.json
  • electron-builder  version=22.2.0 os=4.20.13-arch1-1-ARCH
  • loaded configuration  file=/home/crow/Git/AUR/tagspaces/src/tagspaces-3.4.2/resources/builder.json
  • writing effective config  file=/home/crow/Git/AUR/tagspaces/src/builds/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=7.1.8 appOutDir=/home/crow/Git/AUR/tagspaces/src/builds/linux-unpacked
  ⨯ Application entry file "main.prod.js" in the "/home/crow/Git/AUR/tagspaces/src/builds/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.  stackTrace=
                                                                                                                                                                                  Error: Application entry file "main.prod.js" in the "/home/crow/Git/AUR/tagspaces/src/builds/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
                                                                                                                                                                                      at error (/home/crow/Git/AUR/tagspaces/src/tagspaces-3.4.2/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
                                                                                                                                                                                      at checkFileInArchive (/home/crow/Git/AUR/tagspaces/src/tagspaces-3.4.2/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:33:11)
                                                                                                                                                                                      at LinuxPackager.checkFileInPackage (/home/crow/Git/AUR/tagspaces/src/tagspaces-3.4.2/node_modules/app-builder-lib/src/platformPackager.ts:402:7)
                                                                                                                                                                                      at LinuxPackager.sanityCheckPackage (/home/crow/Git/AUR/tagspaces/src/tagspaces-3.4.2/node_modules/app-builder-lib/src/platformPackager.ts:453:5)
                                                                                                                                                                                      at LinuxPackager.doPack (/home/crow/Git/AUR/tagspaces/src/tagspaces-3.4.2/node_modules/app-builder-lib/src/platformPackager.ts:242:5)
                                                                                                                                                                                      at LinuxPackager.pack (/home/crow/Git/AUR/tagspaces/src/tagspaces-3.4.2/node_modules/app-builder-lib/src/platformPackager.ts:114:5)
                                                                                                                                                                                      at Packager.doBuild (/home/crow/Git/AUR/tagspaces/src/tagspaces-3.4.2/node_modules/app-builder-lib/src/packager.ts:437:9)
                                                                                                                                                                                      at executeFinally (/home/crow/Git/AUR/tagspaces/src/tagspaces-3.4.2/node_modules/app-builder-lib/node_modules/builder-util/src/promise.ts:12:14)
                                                                                                                                                                                      at Packager._build (/home/crow/Git/AUR/tagspaces/src/tagspaces-3.4.2/node_modules/app-builder-lib/src/packager.ts:366:31)
                                                                                                                                                                                      at Packager.build (/home/crow/Git/AUR/tagspaces/src/tagspaces-3.4.2/node_modules/app-builder-lib/src/packager.ts:330:12)
                                                                                                                                                                                      at executeFinally (/home/crow/Git/AUR/tagspaces/src/tagspaces-3.4.2/node_modules/app-builder-lib/node_modules/builder-util/src/promise.ts:12:14)
error Command failed with exit code 1.

**Comment by uggrock** [comment]
Please execute yarn build after the yarn install-ext.
