### ISSUE TITLE
Versions above 3.3.2 (web zip) no longer work out-of-the-box with nextcloud

### ISSUE THREAD

**Issue by james-cook** [tagspaces/tagspaces#1129]
**Describe the bug**
I tried installing the latest 3.5.2, then 3.4.2 then 3.2.1 and finally 3.3.2. This is the last version to work "easily" with nextcloud (version 17).
**Am I missing some new installation documentation?**

**To Reproduce**
1. install tagspaces 3.4.2 or above under apache. If your nextcloud instance is /var/www/nc then install tagspaces in that directory e.g. afterwords you have: /var/www/nc/tagspaces and change permissions as shown in the tagspaces documentation - BTW - this is the setup I've been using since tagspaces 2.9.x
2. in a browser go to your.domain.com/tagspaces
3. the usual dialog - to accept t&cs etc. does not appear from 3.4.2 and above - it briefly "flashes" then disappears. The console shows errors.
4. See error in console output at the end of this text.
In one of the errors:

```
 ChunkLoadError: Loading chunk 5 failed.
(missing: https://xxx.yyy.com/dist/5.bundle.js)
    at Function.o.e (https://xxx.yyy.com/tagspaces/dist/bundle.js:1:747)
    at https://xxx.yyy.com/tagspaces/dist/bundle.js:1:352119
    at https://xxx.yyy.com/tagspaces/dist/bundle.js:113:99016
```
it is noticable that the path "loses" the /tagspaces/ part: 
https://xxx.yyy.com/dist/5.bundle.js should be https://xxx.yyy.com/tagspaces/dist/5.bundle.js

**Expected behavior**
Standard tagspaces behaviour expected. Accepting t&c, redirect for login etc.

**Screenshots**

**Server**
 - Ubuntu 16.04
 - TagSpaces Version 
3.3.2 works fine
3.4.2 ... upwards do not work
Nextcloud version 17.0.6

**Additional context**
This is the console output:
```
Uncaught SyntaxError: Unexpected token '<'
21:05:20.908 bundle.js:1 Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' ".

(anonymous) @ bundle.js:1
onBeforeLift @ bundle.js:1
r.handlePersistorState @ bundle.js:1
p @ bundle.js:129
i @ bundle.js:1
g @ bundle.js:1
(anonymous) @ bundle.js:1
Promise.then (async)
(anonymous) @ bundle.js:1
Promise.then (async)
(anonymous) @ bundle.js:1
p @ bundle.js:129
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
persist @ bundle.js:1
Zt @ bundle.js:1
configureStore @ bundle.js:1
./app/index.tsx @ bundle.js:1
o @ bundle.js:1
./app/app.global.css @ bundle.js:1
(anonymous) @ bundle.js:1
21:05:21.550 bundle.js:1 [Violation] 'setTimeout' handler took 574ms
21:05:21.577 [Violation] Forced reflow while executing JavaScript took 69ms
21:05:21.604 /tagspaces/#/:1 Access to XMLHttpRequest at 'https://www.tagspaces.org/releases/tagspaces.json?cv=3.4.2' from origin 'https://xxx.yyy.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
21:05:21.605 bundle.js:1 GET https://www.tagspaces.org/releases/tagspaces.json?cv=3.4.2 net::ERR_FAILED
(anonymous) @ bundle.js:1
J @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
onBeforeLift @ bundle.js:1
r.handlePersistorState @ bundle.js:1
p @ bundle.js:129
i @ bundle.js:1
g @ bundle.js:1
(anonymous) @ bundle.js:1
Promise.then (async)
(anonymous) @ bundle.js:1
Promise.then (async)
(anonymous) @ bundle.js:1
p @ bundle.js:129
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
persist @ bundle.js:1
Zt @ bundle.js:1
configureStore @ bundle.js:1
./app/index.tsx @ bundle.js:1
o @ bundle.js:1
./app/app.global.css @ bundle.js:1
(anonymous) @ bundle.js:1
21:05:21.974 login:1 Uncaught SyntaxError: Unexpected token '<'
21:05:22.020 login:1 Uncaught SyntaxError: Unexpected token '<'
21:05:22.031 login:1 Uncaught SyntaxError: Unexpected token '<'
21:05:22.044 login:1 Uncaught SyntaxError: Unexpected token '<'
21:05:22.328 bundle.js:113 ChunkLoadError: Loading chunk 5 failed.
(missing: https://xxx.yyy.com/dist/5.bundle.js)
    at Function.o.e (https://xxx.yyy.com/tagspaces/dist/bundle.js:1:747)
    at https://xxx.yyy.com/tagspaces/dist/bundle.js:1:352119
    at https://xxx.yyy.com/tagspaces/dist/bundle.js:113:99016
    at qs (https://xxx.yyy.com/tagspaces/dist/bundle.js:113:99225)
    at zs (https://xxx.yyy.com/tagspaces/dist/bundle.js:113:84104)
    at Fs (https://xxx.yyy.com/tagspaces/dist/bundle.js:113:81131)
    at Ms (https://xxx.yyy.com/tagspaces/dist/bundle.js:113:79704)
    at https://xxx.yyy.com/tagspaces/dist/bundle.js:113:41855
    at t.unstable_runWithPriority (https://xxx.yyy.com/tagspaces/dist/bundle.js:137:3878)
    at co (https://xxx.yyy.com/tagspaces/dist/bundle.js:113:41584)
Mi @ bundle.js:113
Ui.n.callback @ bundle.js:113
Fo @ bundle.js:113
Lo @ bundle.js:113
(anonymous) @ bundle.js:113
t.unstable_runWithPriority @ bundle.js:137
co @ bundle.js:113
Hs @ bundle.js:113
Ms @ bundle.js:113
(anonymous) @ bundle.js:113
t.unstable_runWithPriority @ bundle.js:137
co @ bundle.js:113
ho @ bundle.js:113
L @ bundle.js:137
z @ bundle.js:137
C @ bundle.js:137
21:05:22.334 bundle.js:113 ChunkLoadError: Loading chunk 0 failed.
(missing: https://xxx.yyy.com/dist/0.bundle.js)
    at Function.o.e (https://xxx.yyy.com/tagspaces/dist/bundle.js:1:747)
    at https://xxx.yyy.com/tagspaces/dist/bundle.js:1:352758
    at https://xxx.yyy.com/tagspaces/dist/bundle.js:113:99016
    at qs (https://xxx.yyy.com/tagspaces/dist/bundle.js:113:99225)
    at zs (https://xxx.yyy.com/tagspaces/dist/bundle.js:113:84104)
    at Fs (https://xxx.yyy.com/tagspaces/dist/bundle.js:113:81131)
    at Ms (https://xxx.yyy.com/tagspaces/dist/bundle.js:113:79704)
    at https://xxx.yyy.com/tagspaces/dist/bundle.js:113:41855
    at t.unstable_runWithPriority (https://xxx.yyy.com/tagspaces/dist/bundle.js:137:3878)
    at co (https://xxx.yyy.com/tagspaces/dist/bundle.js:113:41584)
Mi @ bundle.js:113
Ui.n.callback @ bundle.js:113
Fo @ bundle.js:113
Lo @ bundle.js:113
(anonymous) @ bundle.js:113
t.unstable_runWithPriority @ bundle.js:137
co @ bundle.js:113
Hs @ bundle.js:113
Ms @ bundle.js:113
(anonymous) @ bundle.js:113
t.unstable_runWithPriority @ bundle.js:137
co @ bundle.js:113
ho @ bundle.js:113
L @ bundle.js:137
z @ bundle.js:137
C @ bundle.js:137
21:05:22.337 bundle.js:113 ChunkLoadError: Loading chunk 9 failed.
(missing: https://xxx.yyy.com/dist/9.bundle.js)
    at Function.o.e (https://xxx.yyy.com/tagspaces/dist/bundle.js:1:747)
    at https://xxx.yyy.com/tagspaces/dist/bundle.js:1:276254
    at https://xxx.yyy.com/tagspaces/dist/bundle.js:113:99016
    at qs (https://xxx.yyy.com/tagspaces/dist/bundle.js:113:99225)
    at zs (https://xxx.yyy.com/tagspaces/dist/bundle.js:113:84104)
    at Fs (https://xxx.yyy.com/tagspaces/dist/bundle.js:113:81131)
    at Ms (https://xxx.yyy.com/tagspaces/dist/bundle.js:113:79704)
    at https://xxx.yyy.com/tagspaces/dist/bundle.js:113:41855
    at t.unstable_runWithPriority (https://xxx.yyy.com/tagspaces/dist/bundle.js:137:3878)
    at co (https://xxx.yyy.com/tagspaces/dist/bundle.js:113:41584)
Mi @ bundle.js:113
Ui.n.callback @ bundle.js:113
Fo @ bundle.js:113
Lo @ bundle.js:113
(anonymous) @ bundle.js:113
t.unstable_runWithPriority @ bundle.js:137
co @ bundle.js:113
Hs @ bundle.js:113
Ms @ bundle.js:113
(anonymous) @ bundle.js:113
t.unstable_runWithPriority @ bundle.js:137
co @ bundle.js:113
ho @ bundle.js:113
L @ bundle.js:137
z @ bundle.js:137
C @ bundle.js:137
21:05:22.340 bundle.js:1 Uncaught ChunkLoadError: Loading chunk 5 failed.
(missing: https://xxx.yyy.com/dist/5.bundle.js)
    at Function.o.e (https://xxx.yyy.com/tagspaces/dist/bundle.js:1:747)
    at https://xxx.yyy.com/tagspaces/dist/bundle.js:1:352119
    at https://xxx.yyy.com/tagspaces/dist/bundle.js:113:99016
    at qs (https://xxx.yyy.com/tagspaces/dist/bundle.js:113:99225)
    at zs (https://xxx.yyy.com/tagspaces/dist/bundle.js:113:84104)
    at Fs (https://xxx.yyy.com/tagspaces/dist/bundle.js:113:81131)
    at Ms (https://xxx.yyy.com/tagspaces/dist/bundle.js:113:79704)
    at https://xxx.yyy.com/tagspaces/dist/bundle.js:113:41855
    at t.unstable_runWithPriority (https://xxx.yyy.com/tagspaces/dist/bundle.js:137:3878)
    at co (https://xxx.yyy.com/tagspaces/dist/bundle.js:113:41584)
o.e @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:113
qs @ bundle.js:113
zs @ bundle.js:113
Fs @ bundle.js:113
Ms @ bundle.js:113
(anonymous) @ bundle.js:113
t.unstable_runWithPriority @ bundle.js:137
co @ bundle.js:113
ho @ bundle.js:113
fo @ bundle.js:113
Ts @ bundle.js:113
enqueueSetState @ bundle.js:113
x.setState @ bundle.js:129
e @ bundle.js:113
n @ bundle.js:113
(anonymous) @ bundle.js:1
e.emit @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
t.loaded @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:68
ajax @ bundle.js:1
value @ bundle.js:68
value @ bundle.js:68
t.read @ bundle.js:1
t.loadOne @ bundle.js:1
(anonymous) @ bundle.js:1
t.prepareLoading @ bundle.js:1
t.load @ bundle.js:1
t.loadResources @ bundle.js:1
r @ bundle.js:1
t.changeLanguage @ bundle.js:1
l @ bundle.js:1
Show 9 more frames
21:05:22.341 bundle.js:137 [Violation] 'message' handler took 264ms
21:05:22.428 contentscript.js:1052 [Violation] 'requestAnimationFrame' handler took 82ms
21:05:22.801 manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
21:05:23.020 The script resource is behind a redirect, which is disallowed.
```

**Comment by uggrock** [comment]
unfortunately we do not have the capacity to support the WebDAV functionality. If somebody can fix this issue, we will integrate in the code base.

**Comment by james-cook** [comment]
Maybe the title is misleading....
But are you really saying the web version of tagspaces no longer works?

**Comment by uggrock** [comment]
I am saying that we no longer test TagSpaces with Nextcloud, and the library we are using for the WebDAV connection has no updates for years, so unfortunately the webdav part of TagSpaces web is currently not really further developed.

**Comment by disaster123** [comment]
+1 here it's no longer working. Until nextcloud or owncloud support tags i still have to use tagspaces - which no longer works also - really sad

**Comment by james-cook** [comment]
This might be specific to owncloud/nextcloud webdav (and may be a regression there) because others are using more current versions than 3.3.2 in the WEB contexts e.g. #1102 is using 3.4.2...

**Comment by disaster123** [comment]
@james-cook were you able to fix this?

**Comment by disaster123** [comment]
Was anybody able to find another solution for webdav / usage with nextcloud?

**Comment by uggrock** [comment]
webdav version is not supported anymore -> closing
