### ISSUE TITLE
[regression] Problem with file that contains emoji in filename

### ISSUE THREAD

**Issue by byzod** [tagspaces/tagspaces#2066]
**Describe the bug**
File with emoji in filename works in tagspaces-win-x64-5.2.5, breaking when after updated to tagspaces-win-x64-5.7.8

**To Reproduce**
1. Have a video name with emoji
2. Update to tagspaces-win-x64-5.7.8

**Expected behavior**
(tagspaces-win-x64-5.2.5)
![1](https://github.com/tagspaces/tagspaces/assets/848607/07bd961c-caa3-4693-a33b-bdf993dcf5a3)

**Actual behavior**
(tagspaces-win-x64-5.7.8)
![2](https://github.com/tagspaces/tagspaces/assets/848607/f79ada92-3f6f-49fa-a9b4-9cb31002bc16)

**Screenshots**
Tagspace can't even rename it
![3](https://github.com/tagspaces/tagspaces/assets/848607/40544fbe-f153-4785-a722-b8e6e57f69be)

**Desktop Application:**
 - Operating System: [Windows 10]
 - TagSpaces Version [5.7.8]

**Additional context**
Other Unicode characters not tested

**Comment by sytolk** [comment]
you are renaming directory or file? can I have you full file path + unicode character

**Comment by byzod** [comment]
> you are renaming directory or file? can I have you full file path + unicode character

File

`Q:\ACG\Other\H\Short\[error_dll]Do You Like My Cute Dress？ Please Fuck Me Step Brother 💕.mp4`

**Comment by sytolk** [comment]
can't repead this issue on Mac OS.
![image](https://github.com/tagspaces/tagspaces/assets/1415463/c8e88b42-4ae3-4d4f-9856-e042510fc380)
will test later on Windows..

**Comment by byzod** [comment]
> @byzod if you try to delete hidden `.ts` folder (or rename it .ts-tmp) in directory Q:\ACG\Other\H\Short\.ts is this fix file renaming issue? 

no, btw tagspace also failed to tag that file if I delete the old .ts file

---

> Do you have fs watcher enabled?

no 

---

> I cant repeat on windows.. @byzod Can you provide you location settings config?

I don't know where it is, just a `Preferences` file found in `C:\Users\[username]\AppData\Roaming\TagSpaces\` which have too less content that I don't think this is what you want
` {"browser":{"enable_spellchecking":true},"partition":{"per_host_zoom_levels":{"5110153869875687266":{}}},"spellcheck":{"dictionaries":["en"],"dictionary":""}}`

---

>  It will be helpfull if you repeat this issue starting Tagspaces from Debugtron app: https://github.com/pd4d10/debugtron/releases/tag/v0.5.0 and copy here error log after rename file.
>  can you provide steps with renaming this file?

Rename the file:
1. Extract debugtron and x64 zip version (https://www.tagspaces.org/downloads/,  `64bit (zip)`)
2. Start debugtron, drag `TagSpaces.exe` into the drop zone since it didn't recognize it
3. Open it, select location `H\Short`
4. Click on file `[error_dll]Do You Like My Cute Dress？ Please Fuck Me Step Brother 💕.mp4`
5. Press `F2`
6. Change the name and press yes button

log

```

Debugger listening on ws://127.0.0.1:51586/7b362e3a-7546-40df-83b9-8bd895b2f66a
For help, see: https://nodejs.org/en/docs/inspector
Opening file: C:\App\Something\TagSpaces\TagSpaces.exe
Opening file: --inspect=0
Opening file: --remote-debugging-port=0

DevTools listening on ws://127.0.0.1:51599/devtools/browser/ab2cc9de-a063-4fb2-a13d-8c6e7de0e81e
16:52:36.292 > Checking for update
start_ws:49352
Starting Tagspaces WS on C:\App\Something\TagSpaces\resources - pid (2864)
Tagspaces WS: Server running at http://127.0.0.1:49352/ and will accept connections from 127.0.0.1 only
Error occurred in handler for 'loadTextFilePromise': [Error: ENOENT: no such file or directory, open 'Q:\ACG\Other\H\.ts\tsm.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'Q:\\ACG\\Other\\H\\.ts\\tsm.json'
}
Unable to load locale at zh
 Error: Cannot find module './zh/core.json'
    at data (C:\App\Something\TagSpaces\resources\app.asar\dist\main\webpack:\tagspaces\src\renderer\locales\ lazy ^\.*\core\.json$ namespace object:168:12)
    at Object.request (C:\App\Something\TagSpaces\resources\app.asar\dist\main\webpack:\tagspaces\src\renderer\services\i18nOptions.ts:36:35) {
  code: 'MODULE_NOT_FOUND'
}
languageChanged:zh_CN
16:52:37.672 > Error: Error: Cannot find latest.yml in the latest release artifacts (https://github.com/tagspaces/tagspaces/releases/download/v5.7.8/latest.yml): HttpError: 404 
"method: GET url: https://github.com/tagspaces/tagspaces/releases/download/v5.7.8/latest.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": "no-cache",
  "content-encoding": "gzip",
  "content-length": "29",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-type": "text/plain; charset=utf-8",
  "date": "Fri, 15 Mar 2024 08:52:01 GMT",
  "referrer-policy": "no-referrer-when-downgrade",
  "server": "GitHub.com",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "x-content-type-options": "nosniff",
  "x-frame-options": "deny",
  "x-github-request-id": "C99C:1C9002:269244:290B53:65F40C51",
  "x-xss-protection": "0"
}
    at createHttpError (C:\App\Something\TagSpaces\resources\app.asar\dist\main\webpack:\tagspaces\node_modules\builder-util-runtime\out\httpExecutor.js:14:12)
    at i.handleResponse (C:\App\Something\TagSpaces\resources\app.asar\dist\main\webpack:\tagspaces\node_modules\builder-util-runtime\out\httpExecutor.js:116:20)
    at ClientRequest.<anonymous> (C:\App\Something\TagSpaces\resources\app.asar\dist\main\webpack:\tagspaces\node_modules\builder-util-runtime\out\httpExecutor.js:82:26)
    at ClientRequest.emit (node:events:514:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:109316)
    at SimpleURLLoaderWrapper.emit (node:events:514:28)
    at newError (C:\App\Something\TagSpaces\resources\app.asar\dist\main\webpack:\tagspaces\node_modules\builder-util-runtime\out\index.js:47:19)
    at rawData (C:\App\Something\TagSpaces\resources\app.asar\dist\main\webpack:\tagspaces\node_modules\electron-updater\out\providers\GitHubProvider.js:108:54)
    at t.GitHubProvider.info [as getLatestVersion] (C:\App\Something\TagSpaces\resources\app.asar\dist\main\webpack:\tagspaces\node_modules\electron-updater\out\providers\GitHubProvider.js:115:13)
    at f.result [as getUpdateInfoAndProvider] (C:\App\Something\TagSpaces\resources\app.asar\dist\main\webpack:\tagspaces\node_modules\electron-updater\out\AppUpdater.js:319:13)
    at f.doCheckForUpdates (C:\App\Something\TagSpaces\resources\app.asar\dist\main\webpack:\tagspaces\node_modules\electron-updater\out\AppUpdater.js:333:15)
(node:5252) UnhandledPromiseRejectionWarning: Error: Cannot find latest.yml in the latest release artifacts (https://github.com/tagspaces/tagspaces/releases/download/v5.7.8/latest.yml): HttpError: 404 
"method: GET url: https://github.com/tagspaces/tagspaces/releases/download/v5.7.8/latest.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": "no-cache",
  "content-encoding": "gzip",
  "content-length": "29",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-type": "text/plain; charset=utf-8",
  "date": "Fri, 15 Mar 2024 08:52:01 GMT",
  "referrer-policy": "no-referrer-when-downgrade",
  "server": "GitHub.com",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "x-content-type-options": "nosniff",
  "x-frame-options": "deny",
  "x-github-request-id": "C99C:1C9002:269244:290B53:65F40C51",
  "x-xss-protection": "0"
}
    at createHttpError (C:\App\Something\TagSpaces\resources\app.asar\dist\main\webpack:\tagspaces\node_modules\builder-util-runtime\out\httpExecutor.js:14:12)
    at i.handleResponse (C:\App\Something\TagSpaces\resources\app.asar\dist\main\webpack:\tagspaces\node_modules\builder-util-runtime\out\httpExecutor.js:116:20)
    at ClientRequest.<anonymous> (C:\App\Something\TagSpaces\resources\app.asar\dist\main\webpack:\tagspaces\node_modules\builder-util-runtime\out\httpExecutor.js:82:26)
    at ClientRequest.emit (node:events:514:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:109316)
    at SimpleURLLoaderWrapper.emit (node:events:514:28)
    at newError (C:\App\Something\TagSpaces\resources\app.asar\dist\main\webpack:\tagspaces\node_modules\builder-util-runtime\out\index.js:47:19)
    at rawData (C:\App\Something\TagSpaces\resources\app.asar\dist\main\webpack:\tagspaces\node_modules\electron-updater\out\providers\GitHubProvider.js:108:54)
    at t.GitHubProvider.info [as getLatestVersion] (C:\App\Something\TagSpaces\resources\app.asar\dist\main\webpack:\tagspaces\node_modules\electron-updater\out\providers\GitHubProvider.js:115:13)
    at f.result [as getUpdateInfoAndProvider] (C:\App\Something\TagSpaces\resources\app.asar\dist\main\webpack:\tagspaces\node_modules\electron-updater\out\AppUpdater.js:319:13)
    at f.doCheckForUpdates (C:\App\Something\TagSpaces\resources\app.asar\dist\main\webpack:\tagspaces\node_modules\electron-updater\out\AppUpdater.js:333:15)
(Use `TagSpaces --trace-warnings ...` to show where the warning was created)
(node:5252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Error reading directory: [Error: ENOENT: no such file or directory, scandir 'C:\Users\[username]\AppData\Roaming\TagSpaces\tsplugins\@tagspaces\extensions'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\[username]\\AppData\\Roaming\\TagSpaces\\tsplugins\\@tagspaces\\extensions'
}
Error reading directory: [Error: ENOENT: no such file or directory, scandir 'C:\Users\[username]\AppData\Roaming\TagSpaces\tsplugins\@tagspacespro\extensions'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\[username]\\AppData\\Roaming\\TagSpaces\\tsplugins\\@tagspacespro\\extensions'
}
Error occurred in handler for 'loadTextFilePromise': [Error: ENOENT: no such file or directory, open 'Q:\ACG\Other\H\Short\.ts\tsm.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'Q:\\ACG\\Other\\H\\Short\\.ts\\tsm.json'
}
Error listing meta directory Q:\ACG\Other\H\Short\[error_dll]Cute Student Loves To Fuck On The Weekend! Her Tight Pussy Is So Hot❤️🔥.mp4\.ts
Error listing meta directory Q:\ACG\Other\H\Short\[error_dll]Do You Like My Cute Dress？ Please Fuck Me Step Brother 💕.mp4\.ts
Error listing meta directory Q:\ACG\Other\H\Short\[error_dll]I Love Plunging My Dick Into Her Warm Wet Pussy! Step Sister You Are Incredible!💖.mp4\.ts
Error occurred in handler for 'renameDirectoryPromise': Renaming "Q:\ACG\Other\H\Short\[error_dll]Do You Like My Cute Dress？ Please Fuck Me Step Brother 💕.mp4" failed with: Error: ENOENT: no such file or directory, lstat
```

**Comment by sytolk** [comment]
It strange from this log the mp4 file is renamed like a folder..

To get your location settings for `H\Short` : 
1. In Tagspaces click on Edit Location for (H\Short) like this: 
![image](https://github.com/tagspaces/tagspaces/assets/1415463/ff69c350-1d34-4c9e-a9b2-0911392e01d7)
and take screenshot of location settings dialog

**Comment by byzod** [comment]
![2](https://github.com/tagspaces/tagspaces/assets/848607/5bcefba9-b61d-4ae4-b835-aa74f8bbf9e9)

**Comment by byzod** [comment]
?

I can constantly reproduce this issue, and I uploaded logs to prove it's not my incorrect actions. I think next step is try to locate the issue rather than ignore it, yes?

**Comment by sytolk** [comment]
@byzod the problem is that lstat can't find you file to rename it: `Renaming "Q:\ACG\Other\H\Short\[error_dll]....mp4" failed with: Error: ENOENT: no such file or directory, lstat` and this happened on OS level the reasons for this can be many.. including hardware problem with you disk storage. But if you don't have problem to rename files without special characters in file name maybe the problem is in encoding in you OS try to change default encoding to UTF8

**Comment by byzod** [comment]
> @byzod the problem is that lstat can't find you file to rename it: `Renaming "Q:\ACG\Other\H\Short\[error_dll]....mp4" failed with: Error: ENOENT: no such file or directory, lstat` and this happened on OS level the reasons for this can be many.. including hardware problem with you disk storage. But if you don't have problem to rename files without special characters in file name maybe the problem is in encoding in you OS try to change default encoding to UTF8

You mean [this](https://learn.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page)?

![Snipaste_2024-04-03_18-39-36](https://github.com/tagspaces/tagspaces/assets/848607/5b979f63-a19f-4bdc-91cf-a73afd844e4e)


It's not working and breaking many of my apps

The log (seems the same)
```

Debugger listening on ws://127.0.0.1:50409/432e5250-3f1f-4434-b3dc-47293e08cd45
For help, see: https://nodejs.org/en/docs/inspector
Opening file: C:\App\Something\TagSpaces\TagSpaces.exe
Opening file: --inspect=0
Opening file: --remote-debugging-port=0

DevTools listening on ws://127.0.0.1:50422/devtools/browser/ad91f4f5-7391-4606-a531-725cde138720
18:31:25.263 > Checking for update
start_ws:49352
Starting Tagspaces WS on C:\App\Something\TagSpaces\resources - pid (20108)
Tagspaces WS: Server running at http://127.0.0.1:49352/ and will accept connections from 127.0.0.1 only
Error occurred in handler for 'loadTextFilePromise': [Error: ENOENT: no such file or directory, open 'Q:\ACG\Other\H\.ts\tsm.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'Q:\\ACG\\Other\\H\\.ts\\tsm.json'
}
Unable to load locale at zh
 Error: Cannot find module './zh/core.json'
    at data (C:\App\Something\TagSpaces\resources\app.asar\dist\main\webpack:\tagspaces\src\renderer\locales\ lazy ^\.*\core\.json$ namespace object:168:12)
    at Object.request (C:\App\Something\TagSpaces\resources\app.asar\dist\main\webpack:\tagspaces\src\renderer\services\i18nOptions.ts:36:35) {
  code: 'MODULE_NOT_FOUND'
}
languageChanged:zh_CN
Error reading directory: [Error: ENOENT: no such file or directory, scandir 'C:\Users\[username]\AppData\Roaming\TagSpaces\tsplugins\@tagspaces\extensions'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\[username]\\AppData\\Roaming\\TagSpaces\\tsplugins\\@tagspaces\\extensions'
}
Error reading directory: [Error: ENOENT: no such file or directory, scandir 'C:\Users\[username]\AppData\Roaming\TagSpaces\tsplugins\@tagspacespro\extensions'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\[username]\\AppData\\Roaming\\TagSpaces\\tsplugins\\@tagspacespro\\extensions'
}
Error occurred in handler for 'loadTextFilePromise': [Error: ENOENT: no such file or directory, open 'Q:\ACG\Other\H\Short\.ts\tsm.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'Q:\\ACG\\Other\\H\\Short\\.ts\\tsm.json'
}
Error listing meta directory Q:\ACG\Other\H\Short\[error_dll]Cute Student Loves To Fuck On The Weekend! Her Tight Pussy Is So Hot❤️🔥.mp4\.ts
Error listing meta directory Q:\ACG\Other\H\Short\[error_dll]Do You Like My Cute Dress？ Please Fuck Me Step Brother 💕.mp4\.ts
Error listing meta directory Q:\ACG\Other\H\Short\[error_dll]I Love Plunging My Dick Into Her Warm Wet Pussy! Step Sister You Are Incredible!💖.mp4\.ts
Error occurred in handler for 'renameDirectoryPromise': Renaming "Q:\ACG\Other\H\Short\[error_dll]Cute Student Loves To Fuck On The Weekend! Her Tight Pussy Is So Hot❤️🔥.mp4" failed with: Error: ENOENT: no such file or directory, lstat
```

**Comment by sytolk** [comment]
@byzod I cant repeat this issue on my side.. Can you download source code: `git clone https://github.com/tagspaces/tagspaces` `run npm install` `npm run dev` open dev tools (F12) and in Sources Tab 3-dots menu `Open File`  EntryProperties.tsx and set Breakpoint here: https://github.com/tagspaces/tagspaces/blob/develop/src/renderer/components/EntryProperties.tsx#L298 
the problem is that for some unknown reason you mp4 openedEntry.isFile = false -> this means directory. Can you check this?

**Comment by byzod** [comment]
> `git clone https://github.com/tagspaces/tagspaces` `run npm install` `npm run dev`

'git' is not recognized as an internal or external command,
operable program or batch file.

**Comment by byzod** [comment]
Hey I don't know what you did but this issue is fixed in v5.8.6
