### ISSUE TITLE
Unable to package for Windows

### ISSUE THREAD

**Issue by JXatUW** [tagspaces/tagspaces#2084]
**Describe the bug**
Errors occur during packing for windows. I have tried to install it on several different computers(including a brand new Windows 11 virtual machine) and the same error persists.

**To Reproduce**

OS is Windows 11, node version v20.12.1, npm version 10.5.0

1. git clone https://github.com/tagspaces/tagspaces.git
2. cd tagspaces
3. git checkout develop
4. npm install twice according to the guide. **Error during install**: 
![image](https://github.com/tagspaces/tagspaces/assets/166544828/bae28d59-b920-43d7-a046-286f997c3902)
5. npm run install-ext-node **Error during install**
![image](https://github.com/tagspaces/tagspaces/assets/166544828/8482c771-ac9a-45df-a173-42201a0092d9)
6. npm run build **There are some errors** 
```
PS E:\tagspaces> npm run build

> tagspaces@0.0.0 prebuild
> rimraf release/app/dist && npm run prepare-node && npm run generate-extensions


> tagspaces@0.0.0 prepare-node
> npm run install-ext-node-check && npm run postinstall-electron-check


> tagspaces@0.0.0 install-ext-node-check
> npx cross-env PD_PLATFORM=node node scripts/checkWSinstalled.js


> tagspaces@0.0.0 postinstall-electron-check
> cross-env PD_PLATFORM=electron node scripts/postinstall.js


> tagspaces@0.0.0 generate-extensions
> node -r ts-node/register scripts/generateExtensionsConfig.ts

Error reading directory: [Error: ENOENT: no such file or directory, scandir 'E:\tagspaces\release\app\node_modules\@tagspacespro\extensions'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'E:\\tagspaces\\release\\app\\node_modules\\@tagspacespro\\extensions'
}
generateExtensionsConfig: common error:ENOENT: no such file or directory, open 'E:\tagspaces\release\app\node_modules\@tagspaces\extensions\common\package.json'
generateExtensionsConfig: libs error:ENOENT: no such file or directory, open 'E:\tagspaces\release\app\node_modules\@tagspaces\extensions\libs\package.json'
Successfully generated:E:\tagspaces\src\renderer\extension-config.ts

> tagspaces@0.0.0 build
> npm run prebuild && concurrently "npm run build:main" "npm run build:renderer" && node -r ts-node/register ./.erb/scripts/link-modules.ts


> tagspaces@0.0.0 prebuild
> rimraf release/app/dist && npm run prepare-node && npm run generate-extensions


> tagspaces@0.0.0 prepare-node
> npm run install-ext-node-check && npm run postinstall-electron-check


> tagspaces@0.0.0 install-ext-node-check
> npx cross-env PD_PLATFORM=node node scripts/checkWSinstalled.js


> tagspaces@0.0.0 postinstall-electron-check
> cross-env PD_PLATFORM=electron node scripts/postinstall.js


> tagspaces@0.0.0 generate-extensions
> node -r ts-node/register scripts/generateExtensionsConfig.ts

Error reading directory: [Error: ENOENT: no such file or directory, scandir 'E:\tagspaces\release\app\node_modules\@tagspacespro\extensions'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'E:\\tagspaces\\release\\app\\node_modules\\@tagspacespro\\extensions'
}
generateExtensionsConfig: common error:ENOENT: no such file or directory, open 'E:\tagspaces\release\app\node_modules\@tagspaces\extensions\common\package.json'
generateExtensionsConfig: libs error:ENOENT: no such file or directory, open 'E:\tagspaces\release\app\node_modules\@tagspaces\extensions\libs\package.json'
Successfully generated:E:\tagspaces\src\renderer\extension-config.ts
[0]
[0] > tagspaces@0.0.0 build:main
[0] > cross-env NODE_ENV=production TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.main.prod.ts
[0]
[1]
[1] > tagspaces@0.0.0 build:renderer
[1] > cross-env NODE_ENV=production TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.renderer.prod.ts
[1]
[0] npm run build:main exited with code 0
[1] npm run build:renderer exited with code 0
E:\tagspaces\release\app\.env exist
E:\tagspaces\release\app\dist\.env exist
```

9. npm run package-win **Packaging fail**
```
PS E:\tagspaces> npm run package-win

> tagspaces@0.0.0 package-win
> npm run install-ext-node-win && electron-builder --win --x64 --config resources/builder.json


> tagspaces@0.0.0 install-ext-node-win
> rimraf release/app/node_modules && npm install --prefix ./release/app --platform=win32 --arch=x64 && npm run generate-extensions


added 108 packages, and audited 110 packages in 2m

17 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (1 moderate, 4 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> tagspaces@0.0.0 generate-extensions
> node -r ts-node/register scripts/generateExtensionsConfig.ts

generateExtensionsConfig: common error:ENOENT: no such file or directory, open 'E:\tagspaces\release\app\node_modules\@tagspaces\extensions\common\package.json'
generateExtensionsConfig: libs error:ENOENT: no such file or directory, open 'E:\tagspaces\release\app\node_modules\@tagspaces\extensions\libs\package.json'
Error reading directory: [Error: ENOENT: no such file or directory, scandir 'E:\tagspaces\release\app\node_modules\@tagspacespro\extensions'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'E:\\tagspaces\\release\\app\\node_modules\\@tagspacespro\\extensions'
}
Successfully generated:E:\tagspaces\src\renderer\extension-config.ts
  • electron-builder  version=24.9.1 os=10.0.22631
  • loaded configuration  file=E:\tagspaces\resources\builder.json
  • writing effective config  file=E:\builds\builder-effective-config.yaml
  ⨯ open E:\tagspaces\release\app\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\node_modules\tagspaces\package.json: The name of the file cannot be resolved by the system.
github.com/develar/app-builder/pkg/node-modules.(*Collector).resolveDependency
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:197
github.com/develar/app-builder/pkg/node-modules.(*Collector).processDependencies
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:100
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:61
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:77
  ⨯ E:\tagspaces\node_modules\app-builder-bin\win\x64\app-builder.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1  failedTask=build stackTrace=Error: E:\tagspaces\node_modules\app-builder-bin\win\x64\app-builder.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (E:\tagspaces\node_modules\builder-util\src\util.ts:251:14)
    at Object.onceWrapper (node:events:633:26)
    at ChildProcess.emit (node:events:518:28)
    at ChildProcess.cp.emit (E:\tagspaces\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1105:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

**Expected behavior**
I expected it to package an executable file.

**Desktop Application:**
 - Operating System: Windows 11
 - TagSpaces Version: develop branch(same error happens to tag v5.7.12)

**Additional context**
![image](https://github.com/tagspaces/tagspaces/assets/166544828/a682b46d-170f-4796-a793-6698d188399b)
It seems there is an infinite loop in tagspaces\release\app\node_modules\tagspaces, which links to tagspaces\release\app

**Comment by sytolk** [comment]
@JXatUW what is you node.js and npm versions? are you use [nvm](https://github.com/coreybutler/nvm-windows) 
This is my node npm versions:
```
node -v
v18.18.2
npm -v
9.8.1
```
