### ISSUE TITLE
Can't Build A Fully Working Version On Windows

### ISSUE THREAD

**Issue by TheProgrammerJerry** [tagspaces/tagspaces#2209]
**Describe the bug**
Using the github repo and building Tagspaces on windows will open the application, but not fully functional. For example, thumbnail generation does not work. Trying the full application, thumbnails are working. Console reports lots of errors for example:

`
 (node:32104) UnhandledPromiseRejectionWarning: TypeError: Failed to parse URL from http://127.0.0.1:undefined
[1]     at node:internal/deps/undici/undici:13185:13
[1] (Use electron --trace-warnings ... to show where the warning was created)
[1] (node:32104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
`

and

`
pm2.start Exception __dirname:C:\Users\USER\Downloads\tagspaces-6.0.4v3admin\tagspaces-6.0.4\.erb\dll Error: ENOENT: no such file or directory, open 'C:\Users\USER\Downloads\tagspaces-6.0.4v3admin\tagspaces-6.0.4\.erb\.env'
[1]     at readFileSync (node:fs:448:20)
[1]     at t.readFileSync (node:electron/js2c/node_init:2:10175)
[1]     at __webpack_modules__../node_modules/properties-reader/src/properties-reader.js.PropertiesReader.append (C:\Users\USER\Downloads\tagspaces-6.0.4v3admin\tagspaces-6.0.4\.erb\dll\main.bundle.dev.js:24272:19)
[1]     at new PropertiesReader (C:\Users\USER\Downloads\tagspaces-6.0.4v3admin\tagspaces-6.0.4\.erb\dll\main.bundle.dev.js:24196:10)
[1]     at propertiesReaderFactory (C:\Users\USER\Downloads\tagspaces-6.0.4v3admin\tagspaces-6.0.4\.erb\dll\main.bundle.dev.js:24173:12)
[1]     at startWS (C:\Users\USER\Downloads\tagspaces-6.0.4v3admin\tagspaces-6.0.4\.erb\dll\main.bundle.dev.js:53085:84)
[1]     at C:\Users\USER\Downloads\tagspaces-6.0.4v3admin\tagspaces-6.0.4\.erb\dll\main.bundle.dev.js:53290:1
[1]     at C:\Users\USER\Downloads\tagspaces-6.0.4v3admin\tagspaces-6.0.4\.erb\dll\main.bundle.dev.js:53412:3
[1]     at C:\Users\USER\Downloads\tagspaces-6.0.4v3admin\tagspaces-6.0.4\.erb\dll\main.bundle.dev.js:53415:12
[1]     at webpackUniversalModuleDefinition (C:\Users\USER\Downloads\tagspaces-6.0.4v3admin\tagspaces-6.0.4\.erb\dll\main.bundle.dev.js:3:20) {
[1]   errno: -4058,
[1]   code: 'ENOENT',
[1]   syscall: 'open',
[1]   path: 'C:\\Users\\USER\\Downloads\\tagspaces-6.0.4v3admin\\tagspaces-6.0.4\\.erb\\.env'
[1] }
<i> [webpack-dev-middleware] wait until bundle finished: /index.html
Not rewriting GET /extconfig.js because the path includes a dot (.) character.
Not rewriting GET /C:/Users/USER/Pictures/.ts/**SkiWentworth.jpg.jpg** because the path includes a dot (.) character.
`

I have tried a few versions of node now, and have tried building in admin mode to see if it helps. I found some other resolved similar issues but in trying those versions of node and steps I still get the errors (the related ones were mostly around it failing to build, mine will build but won't fully function).

I have also tried the latest develop branch and a few tagged versions to see if it makes a difference.

Note: Using the latest version of Node seems to other issues such as a complaint about Node being a bad property (related to engineDev settings, older Node version tested did not have this issue but it does not appear to be related).

**To Reproduce**
Using the steps in the repo
1. $ git clone https://github.com/tagspaces/tagspaces.git
2. $ cd tagspaces
3. $ git checkout develop
4. $ npm install
5. $ npm run dev
6. Click on an imagine in tagspaces and notice no thumbnail loads

After step 4, I have also tried npm run build and npm run start which has the same result.

**Expected behavior**
When clicking on an imagine I would expect to see its image. I would also expect to see the thumbnail in the file directory within tagspaces - neither show.

**Desktop Application:**
 - Operating System: Windows 10 (Also tried it on a fresh Windows 11 build which had the same results)
 - TagSpaces Version 6.0.4
 - Node Version 18.20.5
 - NPM Version 10.8.2

**Comment by sytolk** [comment]
Hi, in error log its have:  
`Error: ENOENT: no such file or directory, open 'C:\Users\USER\Downloads\tagspaces-6.0.4v3admin\tagspaces-6.0.4.erb.env'`
are you sure that you have .env file?

**Comment by TheProgrammerJerry** [comment]
> Hi, WS is not started in you error log it's have: `Error: ENOENT: no such file or directory, open 'C:\Users\USER\Downloads\tagspaces-6.0.4v3admin\tagspaces-6.0.4.erb.env'` are you sure that you have .env file?
> 
> https://github.com/tagspaces/tagspaces?tab=readme-ov-file#how-to-run-tagspaces-from-the-source-code
> 
> > Starting from v4 of the application, a web service is running locally as a separate process. The web service is responsible for the search index creation and the generation of the thumbnails for most of the images formats. A key is required in order for the main application to communicate with the web server. It should be generated from webpack script in the .env file located in release/app folder. This is an example for an .env file.
> 
> ```
> KEY=a_custom_key
> ```
> 
> my node -v v20.18.0 but should work with node 18 too

Hi there, I am not sure why WS is not loaded and no I don't have that .env file. I do have a env file in the release/app with a KEY=****. 

I am following the build instructions that you linked - which according to output is what creates the above KEY (if you have not made one yet, it uses the default one). I don't see anything in the steps about making a tagspaces-6.0.4.erb.env file - are the build instructions missing a step?

I am not doing anything special - just following the build instructions exactly and in the same order.

**Comment by sytolk** [comment]
Hi, currenty in dev build thumbnails are not showing read this: https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3558
but in package this issue not exist try: `npm run bs`

**Comment by TheProgrammerJerry** [comment]
> Hi, currenty in dev build thumbnails are not showing read this: [electron-react-boilerplate/electron-react-boilerplate#3558](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3558) but in package this issue not exist try: `npm run bs`

If I understand correctly, this bundles it and you run it compiled? IE: this does not run the dev instance.

Has anyone been able to run the dev instance on windows? It seems linux is fine but Windows is my main OS so I can't really run a linux VM to load the tagspaces dev instance (everything I use is in windows).

**Comment by sytolk** [comment]
yes `npm run bs` bundles the tagspaces app and execute it with `electron ./release/app/dist/main/main.js` 
and yes I can run tagspaces `npm run dev` on windows by following this:
https://github.com/tagspaces/tagspaces?tab=readme-ov-file#how-to-run-tagspaces-from-the-source-code
run dev is for development and have hot reload. But if run dev not works for you can you paste the output log from `npm run dev`

**Comment by TheProgrammerJerry** [comment]
> I was looking into it a bit more and I noticed during the build process there was a symlink error reported on the /dist/node_modules directory. After creating the /dist directory and running build again followed by the start dev command, the WS seems to be running. I see thumbnail generation happening. But I am wondering why I had to make this directory and what else I might be missing.

npm run dev works, I just don't see the thumbnails. It seems to all be related to this:

> I was looking into it a bit more and I noticed during the build process there was a symlink error reported on the /dist/node_modules directory. After creating the /dist directory and running build again followed by the start dev command, the WS seems to be running. I see thumbnail generation happening. But I am wondering why I had to make this directory and what else I might be missing.

I am running the guide 100% from the link you posted, https://github.com/tagspaces/tagspaces?tab=readme-ov-file#how-to-run-tagspaces-from-the-source-code

So it seems that there is something else missing. Such as the project needs certain permissions, needs to run from a certain type of command prompt vs. power shell, etc.

I get this issue on both windows 10 and 11. Again, following the steps 100% copy and pasting the commands exactly in the exact order.

The symlink issue seems to drive the WS not to load causing the thumbnails not to generate. The only way I get it to work is by manually creating the /dist folder myself - but some commands remove this so it is a pretty big hassle (this output is in the original post which you have addressed).

I have tried the websecurity setting too from your other link - but that seems to only work after making the /dist change manually.

I can get the app to run 100% correct, just not with the steps in the build guide. It only seems to be an issue in windows.

**Comment by TheProgrammerJerry** [comment]
> I just tried the build instructions on Windows 11 and I was able to build the application. Can you please share the error log so we can try to find the potential cause of the problem.

The error I found was in the first post.

I can build the application, that is not the problem.

The problem is running dev mode when the application loads and you navigate your file system, the thumbnails do not generate. 

Can you confirm your thumbnails are generating and showing after your build in dev mode?

**Comment by TheProgrammerJerry** [comment]
> ok, now I understand. The npm run dev command do not currently support thumbnails, we have an idea how to solve this issue, so it will be fixed soon.

Ok, thank you. I was driving myself mad with this one - glad to hear it is not something I am doing.
