### ISSUE TITLE
Tagspaces Git-build broken on Linux (hangs at splash screen indefinitely)

### ISSUE THREAD

**Issue by sunjam** [tagspaces/tagspaces#299]
Debian 64-bit from Git at 9am PST.  Tagspaces would not close until killed by process.

[9711:0702/092231:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[9711:0702/092231:INFO:audio_manager_pulse.cc(258)] Failed to connect to the context.  Error: Connection refused
[9711:0702/092231:ERROR:process_singleton_posix.cc(277)] Failed to create ./data/SingletonLock: No such file or directory
[9711:0702/092231:ERROR:connection.cc(1060)] Web sqlite error 14, errno -2: unable to open database file, sql: -- sqlite3_open()
[9711:0702/092231:ERROR:web_data_service_backend.cc(54)] Cannot initialize the web database: 1
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[9711:0702/092231:WARNING:nw_form_database_service.cc(21)] initializing autocomplete database failed
[9711:0702/092231:INFO:CONSOLE(62)] ""Loading Loader - Firefox: false | ChromeExt: false | Node: true | Cordova: false | Web: false | isWin: false"", source: file:///home/median/Downloads/tagspaces/data/loader.js (62)
[9711:0702/092232:ERROR:nw_shell.cc(335)] Error: Script error for: tspro
http://requirejs.org/docs/errors.html#scripterror
    at Error (native)
    at C (file:///home/median/Downloads/tagspaces/data/libs/requirejs/require.js:8:302)
    at HTMLScriptElement.i.onScriptError (file:///home/median/Downloads/tagspaces/data/libs/requirejs/require.js:29:514)
[9711:0702/092232:INFO:CONSOLE(8)] "Uncaught Error: Script error for: tspro
http://requirejs.org/docs/errors.html#scripterror", source: file:///home/median/Downloads/tagspaces/data/libs/requirejs/require.js (8)
[9711:0702/092232:INFO:CONSOLE(7)] ""Loading utils.js ..."", source: file:///home/median/Downloads/tagspaces/data/js/utils.js (7)
[9711:0702/092232:INFO:CONSOLE(7)] ""Loading settings.api.js.."", source: file:///home/median/Downloads/tagspaces/data/js/settings.api.js (7)
[9711:0702/092232:INFO:CONSOLE(8)] ""Loading postioapi.js ..."", source: file:///home/median/Downloads/tagspaces/data/js/postioapi.js (8)
[9711:0702/092232:INFO:CONSOLE(12)] ""Loading ioapi.node.js.."", source: file:///home/median/Downloads/tagspaces/data/node-webkit/node-webkit.api.js (12)
[9711:0702/092232:INFO:CONSOLE(6)] ""Loading perspective.manager.js ..."", source: file:///home/median/Downloads/tagspaces/data/js/perspective.manager.js (6)
[9711:0702/092232:INFO:CONSOLE(7)] ""Loading tagutils.js ..."", source: file:///home/median/Downloads/tagspaces/data/js/tagutils.js (7)
[9711:0702/092232:INFO:CONSOLE(8)] ""Loading fileopener..."", source: file:///home/median/Downloads/tagspaces/data/js/fileopener.js (8)
[9711:0702/092232:INFO:CONSOLE(7)] ""Loading tags.ui.js..."", source: file:///home/median/Downloads/tagspaces/data/js/tags.ui.js (7)
[9711:0702/092232:INFO:CONSOLE(7)] ""Loading core.ui.js ..."", source: file:///home/median/Downloads/tagspaces/data/js/core.ui.js (7)
[9711:0702/092232:INFO:CONSOLE(6)] ""Loading search.js ..."", source: file:///home/median/Downloads/tagspaces/data/js/search.js (6)

**Comment by jameskerber** [comment]
Does loader.js contain the following line: `var PRO = "@@PROVERSION";`
If so, try changing it to: `var PRO = "false";`

**Comment by uggrock** [comment]
@sunjam , the suggestion of @jameskerber will solve your issue, thanks for reporting. We should find a better way for loading the pro version...

**Comment by kbrannen** [comment]
I've just found the same issue. Changing line 24 to "false" does not fix it for me; I still get the tspro error. I noticed that the line above that says:  var PRODUCTION = "@@PRODUCTION";
I've set that to both true and false, and neither helps, although "true" creates fewer error messages. Here it is set to "false".

.../data/node-webkit> nw
[19709:1029/212222:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[19728:1029/212222:ERROR:sandbox_linux.cc(325)] InitializeSandbox() called with multiple threads in process gpu-process
[19709:1029/212222:ERROR:cache_util.cc(132)] Unable to move cache folder ../../nwjsdata/GPUCache to ../../nwjsdata/old_GPUCache_000
[19709:1029/212222:ERROR:cache_creator.cc(133)] Unable to create cache
[19709:1029/212222:ERROR:shader_disk_cache.cc(614)] Shader Cache Creation failed: -2
[19709:1029/212223:INFO:CONSOLE(61)] ""Loading Loader - Firefox: false | ChromeExt: false | Node: true | Cordova: false | Web: false | isWin: false"", source: file:///home2/kevin_src/tagspaces/data/loader.js (61)
[19709:1029/212223:ERROR:nw_shell.cc(336)] Error: Script error for: tspro
http://requirejs.org/docs/errors.html#scripterror
    at Error (native)
    at C (file:///home2/kevin_src/tagspaces/data/libs/requirejs/require.js:8:302)
    at HTMLScriptElement.i.onScriptError (file:///home2/kevin_src/tagspaces/data/libs/requirejs/require.js:29:514)
[19709:1029/212223:INFO:CONSOLE(8)] "Uncaught Error: Script error for: tspro
http://requirejs.org/docs/errors.html#scripterror", source: file:///home2/kevin_src/tagspaces/data/libs/requirejs/require.js (8)

(if the var was set to "true" it stops here, if false it continues to spew the rest)

[19709:1029/212223:INFO:CONSOLE(7)] ""Loading utils.js ..."", source: file:///home2/kevin_src/tagspaces/data/js/utils.js (7)
[19709:1029/212223:INFO:CONSOLE(7)] ""Loading settings.api.js.."", source: file:///home2/kevin_src/tagspaces/data/js/settings.api.js (7)
[19709:1029/212223:INFO:CONSOLE(8)] ""Loading postioapi.js ..."", source: file:///home2/kevin_src/tagspaces/data/js/postioapi.js (8)
[19709:1029/212223:INFO:CONSOLE(14)] ""Loading ioapi.node.js.."", source: file:///home2/kevin_src/tagspaces/data/node-webkit/node-webkit.api.js (14)
[19709:1029/212223:INFO:CONSOLE(6)] ""Loading perspective.manager.js ..."", source: file:///home2/kevin_src/tagspaces/data/js/perspective.manager.js (6)
[19709:1029/212223:INFO:CONSOLE(7)] ""Loading tagutils.js ..."", source: file:///home2/kevin_src/tagspaces/data/js/tagutils.js (7)
[19709:1029/212223:INFO:CONSOLE(8)] ""Loading fileopener..."", source: file:///home2/kevin_src/tagspaces/data/js/fileopener.js (8)
[19709:1029/212223:INFO:CONSOLE(7)] ""Loading tags.ui.js..."", source: file:///home2/kevin_src/tagspaces/data/js/tags.ui.js (7)
[19709:1029/212223:INFO:CONSOLE(9)] ""Loading directories.ui.js ..."", source: file:///home2/kevin_src/tagspaces/data/js/directories.ui.js (9)
[19709:1029/212223:INFO:CONSOLE(7)] ""Loading directorybrowser.js ..."", source: file:///home2/kevin_src/tagspaces/data/js/gettingstarted.js (7)
[19709:1029/212223:INFO:CONSOLE(7)] ""Loading core.ui.js ..."", source: file:///home2/kevin_src/tagspaces/data/js/core.ui.js (7)
[19709:1029/212223:INFO:CONSOLE(6)] ""Loading search.js ..."", source: file:///home2/kevin_src/tagspaces/data/js/search.js (6)

This is for commit commit af05e25e944f.

Kevin
