### ISSUE TITLE
Tagspaces Git-build broken on Linux (hangs at splash screen indefinitely) commit af05e25e944f

### ISSUE THREAD

**Issue by kbrannen** [tagspaces/tagspaces#336]
This is a new version of #299 since it's closed. My bad for adding to a closed ticket, I didn't realize that before I clicked save ... sorry!

I've just found the same issue. Changing line 24 to set PRO to "false" does not fix it for me; I still get the tspro error. I noticed that the line above says: var PRODUCTION = "@@PRODUCTION";
I've set that to both true and false, and neither helps, although "true" creates fewer error messages.

.../data/node-webkit> nw
[19709:1029/212222:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[19728:1029/212222:ERROR:sandbox_linux.cc(325)] InitializeSandbox() called with multiple threads in process gpu-process
[19709:1029/212222:ERROR:cache_util.cc(132)] Unable to move cache folder ../../nwjsdata/GPUCache to ../../nwjsdata/old_GPUCache_000
[19709:1029/212222:ERROR:cache_creator.cc(133)] Unable to create cache
[19709:1029/212222:ERROR:shader_disk_cache.cc(614)] Shader Cache Creation failed: -2
[19709:1029/212223:INFO:CONSOLE(61)] ""Loading Loader - Firefox: false | ChromeExt: false | Node: true | Cordova: false | Web: false | isWin: false"", source: file:///home2/kevin_src/tagspaces/data/loader.js (61)
[19709:1029/212223:ERROR:nw_shell.cc(336)] Error: Script error for: tspro
http://requirejs.org/docs/errors.html#scripterror
at Error (native)
at C (file:///home2/kevin_src/tagspaces/data/libs/requirejs/require.js:8:302)
at HTMLScriptElement.i.onScriptError (file:///home2/kevin_src/tagspaces/data/libs/requirejs/require.js:29:514)
[19709:1029/212223:INFO:CONSOLE(8)] "Uncaught Error: Script error for: tspro
http://requirejs.org/docs/errors.html#scripterror", source: file:///home2/kevin_src/tagspaces/data/libs/requirejs/require.js (8)

(if the var was set to "true" it stops here, if false it continues to spew the rest)

[19709:1029/212223:INFO:CONSOLE(7)] ""Loading utils.js ..."", source: file:///home2/kevin_src/tagspaces/data/js/utils.js (7)
[19709:1029/212223:INFO:CONSOLE(7)] ""Loading settings.api.js.."", source: file:///home2/kevin_src/tagspaces/data/js/settings.api.js (7)
[19709:1029/212223:INFO:CONSOLE(8)] ""Loading postioapi.js ..."", source: file:///home2/kevin_src/tagspaces/data/js/postioapi.js (8)
[19709:1029/212223:INFO:CONSOLE(14)] ""Loading ioapi.node.js.."", source: file:///home2/kevin_src/tagspaces/data/node-webkit/node-webkit.api.js (14)
[19709:1029/212223:INFO:CONSOLE(6)] ""Loading perspective.manager.js ..."", source: file:///home2/kevin_src/tagspaces/data/js/perspective.manager.js (6)
[19709:1029/212223:INFO:CONSOLE(7)] ""Loading tagutils.js ..."", source: file:///home2/kevin_src/tagspaces/data/js/tagutils.js (7)
[19709:1029/212223:INFO:CONSOLE(8)] ""Loading fileopener..."", source: file:///home2/kevin_src/tagspaces/data/js/fileopener.js (8)
[19709:1029/212223:INFO:CONSOLE(7)] ""Loading tags.ui.js..."", source: file:///home2/kevin_src/tagspaces/data/js/tags.ui.js (7)
[19709:1029/212223:INFO:CONSOLE(9)] ""Loading directories.ui.js ..."", source: file:///home2/kevin_src/tagspaces/data/js/directories.ui.js (9)
[19709:1029/212223:INFO:CONSOLE(7)] ""Loading directorybrowser.js ..."", source: file:///home2/kevin_src/tagspaces/data/js/gettingstarted.js (7)
[19709:1029/212223:INFO:CONSOLE(7)] ""Loading core.ui.js ..."", source: file:///home2/kevin_src/tagspaces/data/js/core.ui.js (7)
[19709:1029/212223:INFO:CONSOLE(6)] ""Loading search.js ..."", source: file:///home2/kevin_src/tagspaces/data/js/search.js (6)

This is for commit commit af05e25.

Kevin

**Comment by uggrock** [comment]
I just cloned the current master, added the nw files to the data/node-webkit folder and TagSpaces started without any problems.

**Comment by kbrannen** [comment]
I finally had time to get back to this tonight. It seems that I was just really unlucky as to when I cloned. :) The problem is commit af05e25. The very next commit (181034e) fixes it. I can check out each commit and duplicate not working (af) and then working (18). FWIW, the previous commit (02b7589) was broken too. I'm not sure how far back it goes, but I don't think it matters now. Still, it's good to know that I wasn't crazy. :)

So I guess we can close this. :)
