### ISSUE TITLE
Linux version does not run

### ISSUE THREAD

**Issue by probonopd** [tagspaces/tagspaces#710]
```
module.js:545
    throw err;
    ^
Error: Cannot find module '/run/firejail/appimage/.appimage-9986/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
Parent pid 9986, child pid 9990
Parent is shutting down, bye...
module.js:545
    throw err;
    ^
Error: Cannot find module '/run/firejail/appimage/.appimage-9986/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
Parent pid 9986, child pid 9990
Parent is shutting down, bye...
```

May be caused by https://github.com/electron-userland/electron-builder/issues/2958. Please update electron-builder.

References:
* https://github.com/AppImage/appimage.github.io/pull/695
* https://travis-ci.org/AppImage/appimage.github.io/builds/402975611#L625-L635

**Comment by uggrock** [comment]
Fixed for the next release. Thanks for reporting and for the solving hint.
